<h1 style="background-color:DeepSkyBlue;text-align:center";border-property:1px solid blue;border-radius:15px;>Unmasking_Bengaluru's_Air_Quality</h1>

<h3 style="background-color:SkyBlue;">Project Overview </h3>

This project conducts a comprehensive data analysis on security patterns within the city using records spanning 2022 to 2026. The primary purpose is to apply advanced pattern recognition and seasonal anomaly detection techniques to identify significant trend, shifts, and potential vulnerabilities in the urban security landscape. 
By transforming historical data into actionable insights, this study aims to provide a  data-driven perspective on Bangalore's  safety evolution over the past four years.

<h3 style="background-color:SkyBlue;">Data Source </h3>

The dataset used in this project is the Air Quality Dataset for Bengaluru (2022 - 2026).It incudes comprehensive emvironmental metrics recorded over a specific period , offering detailed insights into local pollution patterns.

Source URL : https://zenodo.org/records/18673897?preview_file=bengaluru-in-1277333.zip

Dataset Filename : Dataset: Air Quality Dataset for Bengaluru (2022-08-01 to 2026-02-18)

Analysis Scope : This analysis covers Bangalore's air quality metrics from 2022 to 2026, focusing on pollutant trends like carbon monoxide , nitrogen dioxide, and ozone to infer potential sources from seasonal data.

<h3 style="background-color:SkyBlue;">Attribute Details </h3>

| Attribute Name | Description |
|---|---|
| date | The specific calendar day the air quality measurements were recorded. |
| PM10 | The concentration of inhalable particulate matter with diameters of 10 micrometers or smaller in the air. |
| PM2.5 | The concentration of fine inhalable particulate matter with diameters of 2.5 micrometers or smaller in the air. |
| carbon monoxide | The levels of the colorless, odorless gas produced by the incomplete combustion of fossil fuels. |
| nitrogen dioxide | The concentration of the reactive gas commonly emitted from vehicle exhaust and industrial processes. |
| sulfur dioxide | The levels of the gas produced primarily by the burning of fossil fuels like coal and petroleum. |
| ozone | The concentration of the gas found in the lower atmosphere that acts as a primary component of smog. |
| aerosol optical depth | A measure of how much airborne particles reduce the transmission of light through the atmosphere. |
| dust | The concentration of suspended particulate mineral matter present in the air. |
| UV index | A standard measurement of the strength of ultraviolet radiation from the sun reaching the surface. |
| US air quality index | The standardized numerical scale used by the United States to communicate daily air quality levels. |
| European air quality index | The standardized numerical system used by European agencies to represent the quality of the ambient air. |

<h3 style="background-color:SkyBlue;">Required Libraries </h3>

In [235]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px

<h3 style="background-color:SkyBlue;">Data loading and intial overview </h3>

In [236]:
import numpy as np 
import pandas as pd

<h3 style="background-color:SkyBlue;">Importing Dataset for Analysis </h3>

In [237]:
# Loading the CSV file into dataframe for Analysis
df = pd.read_csv("air_quality_historical.csv")
pd

In [238]:
# Displaying rows and columns of the Dataframe
print("Number of rows:",df.shape[0])
print("Number of columns:",df.shape[1])

Number of rows: 1298
Number of columns: 12

In [239]:
# Displaying first 5 rows of the Dataframe
df.head()

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi,european_aqi
0,2022-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-08-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-08-04,15.242105,10.647368,288.894737,17.910526,4.484211,44.052632,0.19,0.0,0.781579,NaN,NaN
4,2022-08-05,6.137500,4.295833,170.750000,10.245833,2.041667,37.791667,0.05,0.0,0.381250,28.789474,15.263158

In [240]:
# Displaying the last 5 rows of the dataframe
df.tail()

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi,european_aqi
1293,2026-02-14,18.491667,18.091667,411.583333,10.391667,6.037500,92.375000,0.119167,0.083333,2.620833,60.000000,39.666667
1294,2026-02-15,38.187500,37.225000,496.458333,20.950000,13.308333,114.791667,0.254583,1.375000,2.462500,91.458333,58.708333
1295,2026-02-16,46.587500,45.420833,472.375000,10.862500,14.216667,135.416667,0.428333,1.875000,2.327083,118.333333,72.291667
1296,2026-02-17,38.275000,37.441667,464.458333,10.212500,13.937500,130.708333,0.386667,1.416667,2.445833,123.666667,75.333333
1297,2026-02-18,22.191667,21.370833,476.166667,12.208333,10.970833,108.750000,0.203333,1.083333,2.512500,86.833333,60.375000

In [241]:
# Displaying dataset summary, Data types , and non-null values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1298 entries, 0 to 1297
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   date                   1298 non-null   str
 1   pm10                   1295 non-null   float64
 2   pm2_5                  1295 non-null   float64
 3   carbon_monoxide        1295 non-null   float64
 4   nitrogen_dioxide       1295 non-null   float64
 5   sulphur_dioxide        1295 non-null   float64
 6   ozone                  1295 non-null   float64
 7   aerosol_optical_depth  1295 non-null   float64
 8   dust                   1295 non-null   float64
 9   uv_index               1295 non-null   float64
 10  us_aqi                 1294 non-null   float64
 11  european_aqi           1294 non-null   float64
dtypes: float64(11), str(1)
memory usage: 121.8 KB

In [242]:
# Displaying the total number of elements in the dataframe
df.size

15576

In [273]:
#Displaying the summary statistics
df.describe(include='all')

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi,aqi_category,day_category,season,pm_ratio,pm2_5_7d_avg,aqi_change,day_type_season,year
count,1295,1295.000000,1295.000000,1295.000000,1295.000000,1295.000000,1295.000000,1295.000000,1295.000000,1295.000000,1294.000000,1294,1295,1295,1295.000000,1289.000000,1293.000000,1295,1295.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,2,4,NaN,NaN,NaN,8,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Moderate,Weekday,Monsoon,NaN,NaN,NaN,WeekdayMonsoon,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,657,925,424,NaN,NaN,NaN,302,NaN
mean,2024-05-12 00:00:00,29.219668,21.270355,385.913475,16.605452,7.493521,69.933830,0.305166,4.069931,1.894903,68.871816,NaN,NaN,NaN,0.725200,21.281389,0.044888,NaN,2023.844015
min,2022-08-04 00:00:00,0.990000,0.700000,59.040000,0.000000,0.290000,18.960000,0.040000,0.000000,0.160000,14.830000,NaN,NaN,NaN,0.380313,2.684286,-59.920000,NaN,2022.000000
25%,2023-06-23 12:00:00,14.875000,9.815000,284.395000,10.780000,4.480000,45.120000,0.180000,0.170000,1.525000,41.930000,NaN,NaN,NaN,0.644849,11.311429,-6.710000,NaN,2023.000000
50%,2024-05-12 00:00:00,28.310000,20.490000,371.250000,14.510000,6.540000,70.420000,0.270000,1.210000,1.940000,69.580000,NaN,NaN,NaN,0.678904,21.948571,-0.080000,NaN,2024.000000
75%,2025-03-31 12:00:00,41.015000,30.105000,475.835000,20.630000,9.940000,90.875000,0.390000,4.770000,2.270000,91.980000,NaN,NaN,NaN,0.838275,29.705714,7.210000,NaN,2025.000000
max,2026-02-18 00:00:00,107.100000,66.300000,1289.880000,51.000000,20.890000,143.380000,1.040000,72.330000,3.170000,155.580000,NaN,NaN,NaN,0.996454,53.165714,63.380000,NaN,2026.000000
std,NaN,16.555190,12.728857,150.660142,7.973289,3.717388,25.769688,0.164847,7.075915,0.556244,31.918299,NaN,NaN,NaN,0.145986,10.878976,14.204900,NaN,1.074681

<h3 style="background-color:SkyBlue;">Data Cleaning</h3>

In [244]:
# Finding the number of null values present in the dataframe
print(df.isnull().sum())
print("\nTotal missing values:",df.isnull().sum().sum())

date                     0
pm10                     3
pm2_5                    3
carbon_monoxide          3
nitrogen_dioxide         3
sulphur_dioxide          3
ozone                    3
aerosol_optical_depth    3
dust                     3
uv_index                 3
us_aqi                   4
european_aqi             4
dtype: int64

Total missing values: 35

In [245]:
# Finding the number of duplicate values in the dataframe
print("Number of duplicate values:",df.duplicated().sum())

Number of duplicate values: 0

In [274]:
# Displaying the datatype of each column in the dataframe
df.dtypes

date                     datetime64[us]
pm10                            float64
pm2_5                           float64
carbon_monoxide                 float64
nitrogen_dioxide                float64
sulphur_dioxide                 float64
ozone                           float64
aerosol_optical_depth           float64
dust                            float64
uv_index                        float64
us_aqi                          float64
aqi_category                   category
day_category                        str
season                              str
pm_ratio                        float64
pm2_5_7d_avg                    float64
aqi_change                      float64
day_type_season                     str
year                              int32
dtype: object

In [247]:
df = df.drop(columns=['european_aqi'])

In [248]:
# Correcting the datatype from str to datetime
df['date']=pd.to_datetime(df['date'])

In [249]:
# Rounding and limiting the decimal values to two places
df=df.round(2)

C:\Users\shrav\AppData\Local\Temp\ipykernel_23608\150879321.py:2: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  df=df.round(2)

In [250]:
# Finding the number of null values in each row
df.isnull().sum(axis=1)

0       10
1       10
2       10
3        1
4        0
        ..
1293     0
1294     0
1295     0
1296     0
1297     0
Length: 1298, dtype: int64

In [251]:
# Removing the first three rows as the entire rows were null values
df=df.iloc[3:]

In [252]:
# Displaying the first 5 rows
df.head()

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi
3,2022-08-04,15.24,10.65,288.89,17.91,4.48,44.05,0.19,0.00,0.78,NaN
4,2022-08-05,6.14,4.30,170.75,10.25,2.04,37.79,0.05,0.00,0.38,28.79
5,2022-08-06,7.13,4.99,171.62,10.64,1.90,38.21,0.08,0.00,0.58,18.75
6,2022-08-07,7.78,5.42,175.92,11.35,2.01,37.46,0.12,0.08,0.37,21.46
7,2022-08-08,5.72,3.95,145.67,7.02,1.91,43.50,0.15,0.21,1.82,22.25

In [275]:
# Correcting the index value to start from 1
df.index =  range(1,len(df)+1)

In [254]:
# Correcting the null value in us aqi using mean value
df['us_aqi']=df['us_aqi'].fillna(df['us_aqi'].mean)

In [255]:
# Removing all the empty spaces and converting the text in lowercase for better analysis
df.columns=(
    df.columns
    .str.strip()
    .str.lower()
)

In [256]:
#Displaying all the column names
df.columns

Index(['date', 'pm10', 'pm2_5', 'carbon_monoxide', 'nitrogen_dioxide',
       'sulphur_dioxide', 'ozone', 'aerosol_optical_depth', 'dust', 'uv_index',
       'us_aqi'],
      dtype='str')

In [257]:
# Finding the data type of each element in the column 'us_aqi"
print(df['us_aqi'].map(type).value_counts())

us_aqi
<class 'float'>     1294
<class 'method'>       1
Name: count, dtype: int64

In [258]:
# Converting the datatype from method to float
df['us_aqi'] = pd.to_numeric(df['us_aqi'],errors='coerce')

In [259]:
# Creating a new column categorizing aqi into good , moderate and poor which will help in better analysis
df['aqi_category'] = pd.cut(
    df['us_aqi'],
    bins=[-np.inf,50,100,np.inf],
    labels=['Good','Moderate','Poor'],
    right=True
)

In [260]:
# Creating a new column sorting weekdays and weekends which will help analyze when the air quality decreases
df['day_category'] = df['date'].dt.day_of_week.apply(lambda x: 'Weekend' if x>=5 else 'Weekday')

In [261]:
# Creating a new column sorting months into seasons to understand the relation between season and air quality
def get_season(month):
    if month in [12,1,2]:
        return "Winter"
    if month in [3,4,5]:
        return "Summer"
    if month in [6,7,8,9]:
        return "Monsoon"
    else:
        return "Autumn"

df['season'] = df['date'].dt.month.apply(get_season)

In [262]:
# Creating a column that gives us the ratio , which helps to find the reason of the pollution
df['pm_ratio'] = df['pm2_5'] / df['pm10']

In [263]:
# Creating a column that gives us 7 day average of pm2.5
df['pm2_5_7d_avg'] = df['pm2_5'].rolling(7).mean()

In [264]:
# Creating a column that tells us daily change in aqi
df['aqi_change'] = df['us_aqi'].diff()

In [265]:
# Creating a new column that merges the day's category and season that help analyze trends across different periods
df['day_type_season'] = df['day_category'] + df['season']

In [266]:
# Dsiplaying updated columns
df.columns

Index(['date', 'pm10', 'pm2_5', 'carbon_monoxide', 'nitrogen_dioxide',
       'sulphur_dioxide', 'ozone', 'aerosol_optical_depth', 'dust', 'uv_index',
       'us_aqi', 'aqi_category', 'day_category', 'season', 'pm_ratio',
       'pm2_5_7d_avg', 'aqi_change', 'day_type_season'],
      dtype='str')

In [267]:
# Converting the column into datetime type and creating a new column year
df['date'] = pd.to_datetime(df['date'])
df['year'] = df['date'].dt.year

In [268]:
# Checking the unique values in the column 'year'
df['year'].unique()

array([2022, 2023, 2024, 2025, 2026], dtype=int32)

In [269]:
# Grouping the data by year and season to calculate teh average 'us_aqi' for each specific period 
df.groupby(['year','season'])['us_aqi'].mean()

year  season
2022  Autumn     78.464918
      Monsoon    47.078246
      Winter     74.410968
2023  Autumn     75.812459
      Monsoon    38.987869
      Summer     90.365435
      Winter     82.616222
2024  Autumn     81.225902
      Monsoon    34.119344
      Summer     79.672283
      Winter     79.532967
2025  Autumn     72.865410
      Monsoon    35.657705
      Summer     89.887826
      Winter     96.547333
2026  Winter     97.443878
Name: us_aqi, dtype: float64

In [270]:
# Creating a pivot table that organizes the average US AQI by year and season, with years in rows, seasons as columns and the values rounded to two decimal places
df.pivot_table(index='year',columns = 'season',values='us_aqi',aggfunc='mean').round(2)

season  Autumn  Monsoon  Summer  Winter
year
2022     78.46    47.08     NaN   74.41
2023     75.81    38.99   90.37   82.62
2024     81.23    34.12   79.67   79.53
2025     72.87    35.66   89.89   96.55
2026       NaN      NaN     NaN   97.44

In [271]:
# Creating a pivot table that calculates the avg PM ratio, organized by season in the rows and day category in the columns, with the results rounded to two decimal places 
df.pivot_table(index='season',columns = 'day_category',values='pm_ratio',aggfunc='mean').round(2)

day_category  Weekday  Weekend
season
Autumn           0.76     0.76
Monsoon          0.64     0.63
Summer           0.72     0.73
Winter           0.81     0.81

In [272]:
# Calculating and displaying the minimum , maximum and mean values for the PM ratio, along with statistical summary to help determine the cause of the pollution
print(df['pm_ratio'].min().round(2))
print(df['pm_ratio'].max().round(2))
print(df['pm_ratio'].mean().round(2))
print(df['pm_ratio'].describe().round(2))

0.38
1.0
0.73
count    1295.00
mean        0.73
std         0.15
min         0.38
25%         0.64
50%         0.68
75%         0.84
max         1.00
Name: pm_ratio, dtype: float64